# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "mysql:root:123456@tcp(127.0.0.1:3306)/fitness_app"
        table: "users,group_classes,trpg_room"
        descriptionTag: true
        jsonCase: "CamelLower" # 生成json字段时，字段名使用驼峰命名
  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app
